"""Canonical, well-attested micromort values.

These are the entries everyone cites: Ronald Howard's original 1979 estimates,
plus the long-standing table on Wikipedia's "Micromort" article. We hard-code
them here (with sources) so the database has a useful core even if every
scraper is offline.

Each entry is a dict with the same keys as `risks` columns; `tags` is
extracted before insertion. `source_key` references SOURCES.
"""
from __future__ import annotations

SOURCES = {
    "howard1979": dict(
        name="Howard 1979 — On Making Life and Death Decisions",
        url="https://web.stanford.edu/dept/MSandE/cgi-bin/people/faculty/howard/papers.php",
        publisher="Stanford / Ronald A. Howard",
        notes="Original micromort concept paper.",
    ),
    "wiki_micromort": dict(
        name="Wikipedia — Micromort",
        url="https://en.wikipedia.org/wiki/Micromort",
        publisher="Wikipedia",
        notes="Compiled table of activity, transport, and disease micromorts.",
    ),
    "blastland_spiegelhalter": dict(
        name="Blastland & Spiegelhalter — The Norm Chronicles (2013)",
        url="https://understandinguncertainty.org/micromorts",
        publisher="Cambridge / Understanding Uncertainty",
        notes="Popularized micromort/microlife framing; data from UK ONS.",
    ),
    "bmc_skydiving": dict(
        name="USPA Skydiving Fatality Statistics",
        url="https://uspa.org/discover/faqs/safety",
        publisher="United States Parachute Association",
        notes="Annual skydiving fatality reports.",
    ),
    "nhtsa_fars": dict(
        name="NHTSA Fatality Analysis Reporting System (FARS)",
        url="https://www.nhtsa.gov/research-data/fatality-analysis-reporting-system-fars",
        publisher="US DOT NHTSA",
    ),
}

# micromorts column is per single exposure of `exposure` type unless noted.
RISKS: list[dict] = [
    # --- Classic Howard / Wikipedia table -----------------------------------
    dict(
        slug="skydiving-jump-usa",
        name="Skydiving (one jump)",
        category="parachute",
        micromorts=8.0,
        exposure="per_jump",
        exposure_detail="One sport parachute jump, USA",
        population="US skydivers",
        region="US",
        year=2018,
        original_value="~8 µmt/jump",
        original_unit="per jump",
        source_key="bmc_skydiving",
        confidence="medium",
        notes="USPA averages 0.39 fatalities per 100,000 jumps in recent years; "
              "rounded ~8 µmt historically, ~4 µmt for 2010s averages.",
        tags=["extreme-sports", "aviation"],
    ),
    dict(
        slug="scuba-dive",
        name="Scuba dive",
        category="activity",
        micromorts=5.0,
        exposure="per_dive",
        exposure_detail="One recreational scuba dive",
        population="Recreational divers",
        year=2013,
        original_value="~5 µmt/dive",
        original_unit="per dive",
        source_key="wiki_micromort",
        confidence="medium",
        tags=["extreme-sports", "water"],
    ),
    dict(
        slug="marathon-running",
        name="Running a marathon",
        category="activity",
        micromorts=7.0,
        exposure="per_event",
        exposure_detail="One marathon (sudden cardiac death risk during race)",
        year=2012,
        original_value="~7 µmt",
        original_unit="per marathon",
        source_key="wiki_micromort",
        confidence="medium",
        tags=["endurance", "running"],
    ),
    dict(
        slug="hang-gliding",
        name="Hang-gliding flight",
        category="activity",
        micromorts=8.0,
        exposure="per_event",
        exposure_detail="One hang-gliding flight",
        source_key="wiki_micromort",
        confidence="low",
        tags=["aviation", "extreme-sports"],
    ),
    dict(
        slug="mountaineering-everest",
        name="Climbing Mount Everest (summit attempt)",
        category="activity",
        micromorts=37_932.0,
        exposure="per_climb",
        exposure_detail="One Everest summit attempt above base camp",
        year=2017,
        original_value="~1 in 26.4",
        original_unit="per summit attempt",
        source_key="wiki_micromort",
        confidence="medium",
        notes="Long-run summit fatality rate ~3.8%.",
        tags=["mountaineering", "extreme-sports"],
    ),
    dict(
        slug="mountaineering-himalayan-8000m",
        name="Himalayan 8000m climb",
        category="activity",
        micromorts=43_000.0,
        exposure="per_climb",
        exposure_detail="One climb above 8,000 m (excluding Everest)",
        source_key="wiki_micromort",
        confidence="low",
        tags=["mountaineering", "extreme-sports"],
    ),
    dict(
        slug="base-jumping",
        name="BASE jump",
        category="activity",
        micromorts=430.0,
        exposure="per_jump",
        exposure_detail="One BASE jump",
        original_value="~1 in 2,317",
        original_unit="per jump",
        source_key="wiki_micromort",
        confidence="medium",
        tags=["extreme-sports", "aviation"],
    ),

    # --- Howard 1979 originals ---------------------------------------------
    dict(
        slug="motorcycle-6mi-usa-1979",
        name="Motorcycle, 6 miles (Howard 1979)",
        category="transport",
        micromorts=1.0,
        exposure="per_trip",
        exposure_detail="Riding a motorcycle 6 miles in the USA",
        region="US",
        year=1979,
        original_value="1 µmt",
        original_unit="per 6 mile motorcycle trip",
        source_key="howard1979",
        confidence="medium",
        tags=["motorcycle", "historical"],
    ),
    dict(
        slug="car-230mi-usa-1979",
        name="Car, 230 miles (Howard 1979)",
        category="transport",
        micromorts=1.0,
        exposure="per_trip",
        exposure_detail="Driving a car 230 miles in the USA",
        region="US",
        year=1979,
        original_value="1 µmt",
        original_unit="per 230 mile car trip",
        source_key="howard1979",
        confidence="medium",
        tags=["car", "historical"],
    ),
    dict(
        slug="bicycle-10mi-usa-1979",
        name="Bicycle, 10 miles (Howard 1979)",
        category="transport",
        micromorts=1.0,
        exposure="per_trip",
        exposure_detail="Cycling 10 miles in the USA",
        region="US",
        year=1979,
        original_value="1 µmt",
        original_unit="per 10 mile bicycle trip",
        source_key="howard1979",
        confidence="medium",
        tags=["bicycle", "historical"],
    ),
    dict(
        slug="airliner-1000mi-1979",
        name="Commercial airliner, 1,000 miles (Howard 1979)",
        category="transport",
        micromorts=1.0,
        exposure="per_trip",
        exposure_detail="Flying 1,000 miles on a commercial airliner",
        year=1979,
        original_value="1 µmt",
        original_unit="per 1000 mile flight",
        source_key="howard1979",
        confidence="medium",
        tags=["aviation", "historical"],
    ),

    # --- Modern UK transport (Blastland & Spiegelhalter) -------------------
    dict(
        slug="walking-uk-per-mile",
        name="Walking (1 mile, UK)",
        category="transport",
        micromorts=0.04,
        exposure="per_mile",
        exposure_detail="Walking 1 mile, UK pedestrians",
        region="UK",
        source_key="blastland_spiegelhalter",
        confidence="medium",
        tags=["pedestrian"],
    ),
    dict(
        slug="cycling-uk-per-mile",
        name="Cycling (1 mile, UK)",
        category="transport",
        micromorts=0.07,
        exposure="per_mile",
        exposure_detail="Cycling 1 mile, UK",
        region="UK",
        source_key="blastland_spiegelhalter",
        confidence="medium",
        tags=["bicycle"],
    ),
    dict(
        slug="motorcycle-uk-per-mile",
        name="Motorcycle (1 mile, UK)",
        category="transport",
        micromorts=0.40,
        exposure="per_mile",
        exposure_detail="Riding a motorcycle 1 mile, UK",
        region="UK",
        source_key="blastland_spiegelhalter",
        confidence="medium",
        tags=["motorcycle"],
    ),
    dict(
        slug="car-uk-per-mile",
        name="Car (1 mile, UK)",
        category="transport",
        micromorts=0.005,
        exposure="per_mile",
        exposure_detail="Driving a car 1 mile, UK",
        region="UK",
        source_key="blastland_spiegelhalter",
        confidence="medium",
        tags=["car"],
    ),

    # --- Medical ------------------------------------------------------------
    dict(
        slug="general-anaesthesia",
        name="General anaesthesia",
        category="medical",
        micromorts=5.0,
        exposure="per_event",
        exposure_detail="One administration of general anaesthesia (modern, healthy patient)",
        original_value="1 in 200,000",
        original_unit="per anaesthesia",
        source_key="wiki_micromort",
        confidence="medium",
        tags=["surgery"],
    ),
    dict(
        slug="giving-birth-uk",
        name="Giving birth (UK, modern)",
        category="medical",
        micromorts=120.0,
        exposure="per_event",
        exposure_detail="Maternal death per delivery, UK",
        region="UK",
        original_value="~12 per 100,000 deliveries",
        original_unit="per delivery",
        source_key="blastland_spiegelhalter",
        confidence="medium",
        tags=["pregnancy"],
    ),

    # --- Lifestyle (background per-day risk reference points) --------------
    dict(
        slug="background-mortality-uk-avg-day",
        name="Average background mortality (UK, one day)",
        category="baseline",
        micromorts=39.0,
        exposure="per_day",
        exposure_detail="UK population-average all-cause mortality per day",
        region="UK",
        original_value="~1 in 25,600 per day (population average)",
        original_unit="per day",
        source_key="blastland_spiegelhalter",
        confidence="high",
        notes="A useful zero-point: how much risk you accept by being alive for one day.",
        tags=["baseline"],
    ),

    # --- Misc / environmental ----------------------------------------------
    dict(
        slug="lightning-strike-usa-year",
        name="Lightning strike (USA, one year)",
        category="environmental",
        micromorts=0.05,
        exposure="per_year",
        exposure_detail="Killed by lightning, average US resident",
        region="US",
        original_value="~1 in 20,000,000 per year",
        original_unit="per year",
        source_key="wiki_micromort",
        confidence="medium",
        tags=["weather"],
    ),
    dict(
        slug="ecstasy-mdma-tablet",
        name="Taking an Ecstasy (MDMA) tablet",
        category="drugs",
        micromorts=0.5,
        exposure="per_event",
        exposure_detail="One MDMA tablet",
        region="UK",
        original_value="~1 in 2,000,000 per pill",
        original_unit="per tablet",
        source_key="blastland_spiegelhalter",
        confidence="low",
        tags=["drugs"],
    ),
]
